# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, 
#skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as 
#we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust Node.js version as needed

      - name: Install Love2D globally
        run: npm install -g love.js

      - name: Compress entire repository into FastPong.love
        run: zip -r FastPong.love .  # Compress everything (adjust path if needed)

      - name: Build game with Love2D
        # Replace 'dist' with your actual output directory
        run: love.js FastPong.love ./dist --title "FastPong"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: game-build
          path: dist/  # Upload contents of the dist folder
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
